[tool.poetry]
name = "mammogram"
version = "0.1.0"
description = ""
authors = ["solera <cvalverde@irvinecompany.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
